export const ADMIN_GAMES_REQUEST = 'ADMIN_GAMES_REQUEST'
export const ADMIN_GAMES_SUCCESS = 'ADMIN_GAMES_SUCCESS'
export const ADMIN_GAMES_FAIL = 'ADMIN_GAMES_FAIL'

export const ALL_GAMES_REQUEST = 'ALL_GAMES_REQUEST'
export const ALL_GAMES_SUCCESS = 'ALL_GAMES_SUCCESS'
export const ALL_GAMES_FAIL = 'ALL_GAMES_FAIL'

export const NEW_GAME_REQUEST = 'NEW_GAME_REQUEST'
export const NEW_GAME_SUCCESS = 'NEW_GAME_SUCCESS'
export const NEW_GAME_RESET = 'NEW_GAME_RESET'
export const NEW_GAME_FAIL = 'NEW_GAME_FAIL'

export const DELETE_GAME_REQUEST = 'DELETE_GAME_REQUEST'
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS'
export const DELETE_GAME_RESET = 'DELETE_GAME_RESET'
export const DELETE_GAME_FAIL = 'DELETE_GAME_FAIL'

export const UPDATE_GAME_REQUEST = 'UPDATE_GAME_REQUEST'
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS'
export const UPDATE_GAME_RESET = 'UPDATE_GAME_RESET'
export const UPDATE_GAME_FAIL = 'UPDATE_GAME_FAIL'

export const GAME_DETAILS_REQUEST = 'GAME_DETAILS_REQUEST'
export const GAME_DETAILS_SUCCESS = 'GAME_DETAILS_SUCCESS'
export const GAME_DETAILS_FAIL = 'GAME_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'